import mysql from 'mysql2/promise';
const sql = `
CREATE TABLE IF NOT EXISTS roles (id BIGINT PRIMARY KEY AUTO_INCREMENT, name ENUM('owner','admin','manager') NOT NULL UNIQUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS users (id BIGINT PRIMARY KEY AUTO_INCREMENT, email VARCHAR(255) NOT NULL UNIQUE, username VARCHAR(100) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, role_id BIGINT NOT NULL, suspended BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(role_id) REFERENCES roles(id));
CREATE TABLE IF NOT EXISTS permissions (id BIGINT PRIMARY KEY AUTO_INCREMENT, code VARCHAR(100) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS role_permissions (role_id BIGINT NOT NULL, permission_id BIGINT NOT NULL, decision ENUM('allow','deny','approval_required') NOT NULL, PRIMARY KEY(role_id,permission_id), FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE, FOREIGN KEY(permission_id) REFERENCES permissions(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS user_permissions (user_id BIGINT NOT NULL, permission_id BIGINT NOT NULL, decision ENUM('allow','deny','approval_required') NOT NULL, PRIMARY KEY(user_id,permission_id), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(permission_id) REFERENCES permissions(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS server_assignments (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, server_id VARCHAR(64) NOT NULL, permissions JSON NOT NULL, assigned_by BIGINT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY assignment_unique(user_id,server_id), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(assigned_by) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS approval_requests (id CHAR(36) PRIMARY KEY, requester_id BIGINT NOT NULL, action VARCHAR(100) NOT NULL, target_type VARCHAR(40) NOT NULL, target_id VARCHAR(64), server_id VARCHAR(64), payload JSON NOT NULL, reason TEXT NOT NULL, status ENUM('pending','approved','rejected','failed','cancelled','expired') NOT NULL DEFAULT 'pending', execution_token CHAR(36) UNIQUE, reviewed_by BIGINT, reviewed_at TIMESTAMP NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(requester_id) REFERENCES users(id), FOREIGN KEY(reviewed_by) REFERENCES users(id), INDEX(status,created_at));
CREATE TABLE IF NOT EXISTS audit_logs (id BIGINT PRIMARY KEY AUTO_INCREMENT, actor_id BIGINT, action VARCHAR(100) NOT NULL, resource_type VARCHAR(40) NOT NULL, resource_id VARCHAR(64), server_id VARCHAR(64), result ENUM('success','denied','failed','pending') NOT NULL, ip VARCHAR(64), user_agent VARCHAR(512), request_id CHAR(36), metadata JSON, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX(server_id,created_at), INDEX(actor_id,created_at));
CREATE TABLE IF NOT EXISTS api_connections (id BIGINT PRIMARY KEY AUTO_INCREMENT, base_url VARCHAR(255) NOT NULL, application_key_ciphertext TEXT NOT NULL, client_key_ciphertext TEXT NOT NULL, enabled BOOLEAN DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS notifications (id CHAR(36) PRIMARY KEY, user_id BIGINT NOT NULL, type VARCHAR(80) NOT NULL, title VARCHAR(255) NOT NULL, body TEXT NOT NULL, read_at TIMESTAMP NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX(user_id,read_at));
CREATE TABLE IF NOT EXISTS sessions (id CHAR(64) PRIMARY KEY, user_id BIGINT NOT NULL, csrf_token CHAR(64) NOT NULL, expires_at TIMESTAMP NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX(expires_at));
CREATE TABLE IF NOT EXISTS settings (setting_key VARCHAR(100) PRIMARY KEY, setting_value JSON NOT NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
INSERT IGNORE INTO roles(name) VALUES ('owner'),('admin'),('manager');`;
const pool=await mysql.createPool(process.env.DATABASE_URL!).getConnection(); try { for(const statement of sql.split(';').map(s=>s.trim()).filter(Boolean)) await pool.query(statement); } finally {pool.release();}
