import Fastify, { type FastifyRequest } from 'fastify';
import cookie from '@fastify/cookie'; import helmet from '@fastify/helmet'; import rateLimit from '@fastify/rate-limit'; import statik from '@fastify/static';
import path from 'node:path'; import crypto from 'node:crypto'; import { z } from 'zod';
import { loadConfig } from './config.js'; import { db } from './db/pool.js'; import { currentSession, createSession, revokeSession, verifyPassword } from './auth/session.js'; import { decide, assertAssignment } from './auth/policy.js'; import { PterodactylGateway } from './services/pterodactyl.js'; import { audit } from './services/audit.js'; import { requestApproval, claimApproval } from './services/approval.js';
import type { Actor, Assignment, Decision } from './types/domain.js';

type RequestWithActor=FastifyRequest & { actor?: Actor & { csrf_token:string } };
const config=loadConfig(); const app=Fastify({logger:{redact:['req.headers.authorization','req.headers.cookie','req.body.password','req.body.currentPassword','*.token','*.key']},genReqId:()=>crypto.randomUUID()});
await app.register(cookie); await app.register(helmet,{global:true}); await app.register(rateLimit,{global:true,max:180,timeWindow:'1 minute'}); await app.register(statik,{root:path.join(process.cwd(),'public')});
const ptero=new PterodactylGateway(config);
const code=(status:number,message:string)=>Object.assign(new Error(message),{statusCode:status});
const pathSchema=z.string().max(1024).refine(v=>!v.includes('\0')&&!v.split('/').includes('..'),'Unsafe file path');
function actor(req:RequestWithActor){if(!req.actor)throw code(401,'Authentication required');return req.actor;}
async function permissionMap(userId:number,table:'role_permissions'|'user_permissions'){const [rows]=await db.query<any[]>(`SELECT p.code, ${table}.decision FROM ${table} JOIN permissions p ON p.id=${table}.permission_id ${table==='role_permissions'?'JOIN users u ON u.role_id=role_permissions.role_id WHERE u.id=?':'WHERE user_permissions.user_id=?'}`,[userId]);return Object.fromEntries(rows.map(r=>[r.code,r.decision])) as Record<string,Decision>;}
async function assigned(userId:number,serverId:string){const [rows]=await db.query<any[]>('SELECT server_id AS serverId, permissions FROM server_assignments WHERE user_id=? AND server_id=?',[userId,serverId]);return rows[0]?{serverId:rows[0].serverId,permissions:typeof rows[0].permissions==='string'?JSON.parse(rows[0].permissions):rows[0].permissions} as Assignment:undefined;}
async function authorize(req:RequestWithActor,permission:string,serverId?:string){const user=actor(req);const asn=serverId?await assigned(user.id,serverId):undefined;if(serverId)assertAssignment(user,serverId,asn?[asn]:[]);const decision=decide(user,permission,await permissionMap(user.id,'role_permissions'),asn,await permissionMap(user.id,'user_permissions'));if(decision==='deny')throw code(403,'You do not have permission to perform this action');return {user,decision};}
async function auditRequest(req:RequestWithActor,action:string,result:'success'|'denied'|'failed'|'pending',serverId?:string,metadata?:unknown){await audit({actorId:req.actor?.id,action,resourceType:serverId?'server':'panel',resourceId:serverId,serverId,result,requestId:req.id,ip:req.ip,userAgent:req.headers['user-agent'],metadata});}
async function action(req:RequestWithActor,reply:any,permission:string,serverId:string,targetType:string,targetId:string|undefined,run:()=>Promise<unknown>){const {user,decision}=await authorize(req,permission,serverId);if(decision==='approval_required'){const id=await requestApproval({requesterId:user.id,action:permission,targetType,targetId,serverId,payload:req.body,reason:z.object({reason:z.string().trim().min(3).max(1000).optional()}).passthrough().parse(req.body||{}).reason||'No reason supplied'});await auditRequest(req,permission,'pending',serverId,{approvalId:id});return reply.code(202).send({success:true,data:{approvalRequestId:id,status:'pending'}});}try{const data=await run();await auditRequest(req,permission,'success',serverId);return {success:true,data};}catch(error){await auditRequest(req,permission,'failed',serverId);throw error;}}
app.addHook('onRequest',async(req,reply)=>{const session=await currentSession(req.cookies.session);(req as RequestWithActor).actor=session||undefined;if(!['GET','HEAD','OPTIONS'].includes(req.method)&&req.url!=='/api/auth/login'&&session&&req.headers['x-csrf-token']!==session.csrf_token)return reply.code(403).send({success:false,error:{code:'CSRF_INVALID',message:'Invalid CSRF token'},request_id:req.id});});
app.setErrorHandler((error:any,req,reply)=>{const status=error.statusCode||500;if(status>=500)req.log.error({err:error,request_id:req.id},'request failed');reply.code(status).send({success:false,error:{code:status===401?'UNAUTHENTICATED':status===403?'FORBIDDEN':status===422?'VALIDATION_ERROR':'REQUEST_FAILED',message:status>=500?'Service temporarily unavailable':error.message},request_id:req.id});});
app.post('/api/auth/login',{config:{rateLimit:{max:5,timeWindow:'15 minutes'}}},async(req:any,reply)=>{const input=z.object({email:z.string().email().max(255),password:z.string().min(1).max(1024)}).parse(req.body);const [rows]=await db.query<any[]>('SELECT u.*,r.name role FROM users u JOIN roles r ON r.id=u.role_id WHERE u.email=? AND u.suspended=0',[input.email.toLowerCase()]);if(!rows[0]||!await verifyPassword(input.password,rows[0].password_hash)){await audit({action:'auth.login_failed',resourceType:'user',result:'denied',requestId:req.id,ip:req.ip,userAgent:req.headers['user-agent']});throw code(401,'Invalid credentials');}await db.execute('UPDATE users SET last_login_at=NOW(),last_activity_at=NOW() WHERE id=?',[rows[0].id]);const session=await createSession(rows[0].id);reply.setCookie('session',session.id,{httpOnly:true,sameSite:'strict',secure:config.NODE_ENV==='production',path:'/',maxAge:43_200});await audit({actorId:rows[0].id,action:'auth.login',resourceType:'session',result:'success',requestId:req.id,ip:req.ip,userAgent:req.headers['user-agent']});return {success:true,data:{csrfToken:session.csrf,user:{id:rows[0].id,email:rows[0].email,username:rows[0].username,role:rows[0].role}}};});
app.post('/api/auth/logout',async(req:any,reply)=>{const user=actor(req);if(req.cookies.session)await revokeSession(req.cookies.session);await auditRequest(req,'auth.logout','success');reply.clearCookie('session',{path:'/'});return reply.code(204).send();});
app.get('/api/me',async(req:any)=>{const user=actor(req);return {success:true,data:{user,permissions:await permissionMap(user.id,'role_permissions')}};});
app.get('/api/servers',async(req:any)=>{const user=actor(req);const page=z.coerce.number().int().min(1).default(1).parse(req.query.page);const result:any=await ptero.application(`/servers?include=allocations,user&page=${page}`);if(user.role==='owner')return {success:true,data:result};const [rows]=await db.query<any[]>('SELECT server_id FROM server_assignments WHERE user_id=?',[user.id]);const ids=new Set(rows.map(r=>String(r.server_id)));result.data=(result.data||[]).filter((s:any)=>ids.has(String(s.attributes?.id))||ids.has(String(s.attributes?.identifier)));return {success:true,data:result};});
app.get('/api/servers/:serverId',async(req:any)=>{const id=z.string().max(64).parse(req.params.serverId);await authorize(req,'server.view',id);return {success:true,data:await ptero.application(`/servers/${encodeURIComponent(id)}?include=allocations,variables,user`)}});
function serverGet(url:string,perm:string){app.get(url,async(req:any)=>{const id=z.string().max(64).parse(req.params.serverId);await authorize(req,perm,id);return {success:true,data:await ptero.client(`/servers/${encodeURIComponent(id)}${req.params.tail||''}`)}});}
serverGet('/api/servers/:serverId/resources','resource.view');serverGet('/api/servers/:serverId/backups','backup.view');serverGet('/api/servers/:serverId/databases','database.view');serverGet('/api/servers/:serverId/schedules','schedule.view');serverGet('/api/servers/:serverId/startup','startup.view');serverGet('/api/servers/:serverId/subusers','server.subusers.view');serverGet('/api/servers/:serverId/network/allocations','allocation.view');
app.get('/api/servers/:serverId/files/list',async(req:any)=>{const id=z.string().max(64).parse(req.params.serverId),directory=pathSchema.parse(req.query.directory||'/');await authorize(req,'files.view',id);return {success:true,data:await ptero.client(`/servers/${encodeURIComponent(id)}/files/list?directory=${encodeURIComponent(directory)}`)}});
app.get('/api/servers/:serverId/files/contents',async(req:any)=>{const id=z.string().max(64).parse(req.params.serverId),file=pathSchema.parse(req.query.file);await authorize(req,'files.read',id);return {success:true,data:await ptero.client(`/servers/${encodeURIComponent(id)}/files/contents?file=${encodeURIComponent(file)}`)}});
app.get('/api/servers/:serverId/files/upload-url',async(req:any)=>{const id=z.string().max(64).parse(req.params.serverId);await authorize(req,'files.upload',id);return {success:true,data:await ptero.client(`/servers/${encodeURIComponent(id)}/files/upload`)}});
app.post('/api/servers/:serverId/power',{config:{rateLimit:{max:12,timeWindow:'1 minute'}}},async(req:any,reply)=>{const id=z.string().max(64).parse(req.params.serverId),signal=z.object({signal:z.enum(['start','stop','restart','kill'])}).parse(req.body).signal;return action(req,reply,`console.${signal}`,id,'server',id,()=>ptero.client(`/servers/${encodeURIComponent(id)}/power`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({signal})}));});
app.post('/api/servers/:serverId/command',{config:{rateLimit:{max:30,timeWindow:'1 minute'}}},async(req:any,reply)=>{const id=z.string().max(64).parse(req.params.serverId),command=z.object({command:z.string().trim().min(1).max(2048)}).parse(req.body).command;return action(req,reply,'console.command',id,'server',id,()=>ptero.client(`/servers/${encodeURIComponent(id)}/command`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command})}));});
const filePost=z.object({root:pathSchema,files:z.array(pathSchema).max(100)});
app.post('/api/servers/:serverId/files/write',async(req:any,reply)=>{const id=z.string().max(64).parse(req.params.serverId),body=z.object({file:pathSchema,content:z.string().max(2_000_000)}).parse(req.body);return action(req,reply,'files.write',id,'file',body.file,()=>ptero.client(`/servers/${encodeURIComponent(id)}/files/write?file=${encodeURIComponent(body.file)}`,{method:'POST',headers:{'Content-Type':'text/plain'},body:body.content}));});
app.post('/api/servers/:serverId/files/create-folder',async(req:any,reply)=>{const id=z.string().max(64).parse(req.params.serverId),body=z.object({root:pathSchema,name:z.string().min(1).max(255).refine(n=>!/[\\/\0]/.test(n))}).parse(req.body);return action(req,reply,'files.write',id,'file',body.name,()=>ptero.client(`/servers/${encodeURIComponent(id)}/files/create-folder`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}));});
app.delete('/api/servers/:serverId/files',async(req:any,reply)=>{const id=z.string().max(64).parse(req.params.serverId),body=filePost.parse(req.body);return action(req,reply,'files.delete',id,'file',undefined,()=>ptero.client(`/servers/${encodeURIComponent(id)}/files/delete`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}));});
app.post('/api/servers/:serverId/backups',async(req:any,reply)=>{const id=z.string().max(64).parse(req.params.serverId),body=z.object({name:z.string().trim().min(1).max(191),isLocked:z.boolean().optional()}).parse(req.body);return action(req,reply,'backup.create',id,'backup',undefined,()=>ptero.client(`/servers/${encodeURIComponent(id)}/backups`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}));});
app.delete('/api/servers/:serverId/backups/:backupId',async(req:any,reply)=>{const id=z.string().max(64).parse(req.params.serverId),backup=z.string().uuid().parse(req.params.backupId);return action(req,reply,'backup.delete',id,'backup',backup,()=>ptero.client(`/servers/${encodeURIComponent(id)}/backups/${backup}`,{method:'DELETE'}));});
app.post('/api/servers/:serverId/databases',async(req:any,reply)=>{const id=z.string().max(64).parse(req.params.serverId),body=z.object({database:z.string().regex(/^[a-zA-Z0-9_-]{1,48}$/),remote:z.string().max(255).default('%')}).parse(req.body);return action(req,reply,'database.create',id,'database',undefined,()=>ptero.client(`/servers/${encodeURIComponent(id)}/databases`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}));});
app.get('/health',async()=>({success:true,data:{status:'ok'}}));app.get('/ready',async(_req,reply)=>{try{await db.query('SELECT 1');return {success:true,data:{status:'ok'}};}catch{return reply.code(503).send({success:false,error:{code:'NOT_READY',message:'Database unavailable'}});}});app.get('/',async(_req,reply)=>reply.sendFile('index.html'));
async function shutdown(){await app.close();await db.end();}process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);await app.listen({host:config.HOST,port:config.PORT});
