import Fastify from 'fastify'; import cookie from '@fastify/cookie'; import helmet from '@fastify/helmet'; import rateLimit from '@fastify/rate-limit'; import statik from '@fastify/static'; import path from 'node:path'; import { z } from 'zod'; import crypto from 'node:crypto';
import { db } from './db/pool.js'; import { createSession,currentSession,verifyPassword } from './auth/session.js'; import { assertAssignment,decide } from './auth/policy.js'; import { PterodactylGateway } from './services/pterodactyl.js'; import { claimApproval,requestApproval } from './services/approval.js';
const app=Fastify({logger:{redact:['req.headers.authorization','req.headers.cookie','*.password','*.token','*.key']}}); await app.register(cookie); await app.register(helmet); await app.register(rateLimit,{max:120,timeWindow:'1 minute'});
await app.register(statik,{root:path.join(process.cwd(),'public')});
const gate=new PterodactylGateway();
app.addHook('onRequest',async(req,reply)=>{ const session=await currentSession(req.cookies.session); (req as any).actor=session; if(req.method!=='GET'&&req.method!=='HEAD'&&req.url!=='/api/auth/login'&&session&&req.headers['x-csrf-token']!==session.csrf_token) return reply.code(403).send({error:'Invalid CSRF token'}); });
function actor(req:any){if(!req.actor)throw Object.assign(new Error('Authentication required'),{statusCode:401}); return req.actor;}
async function rules(userId:number){const [r]=await db.query<any[]>('SELECT p.code,rp.decision FROM users u JOIN role_permissions rp ON rp.role_id=u.role_id JOIN permissions p ON p.id=rp.permission_id WHERE u.id=?',[userId]); return Object.fromEntries(r.map(x=>[x.code,x.decision]));}
async function assignment(userId:number,id:string){const [r]=await db.query<any[]>('SELECT server_id AS serverId,permissions FROM server_assignments WHERE user_id=? AND server_id=?',[userId,id]); return r[0]&&{...r[0],permissions:JSON.parse(r[0].permissions)};}
async function authorize(req:any, permission:string, serverId?:string){const a=actor(req), asn=serverId?await assignment(a.id,serverId):undefined; if(serverId)assertAssignment(a,serverId,asn?[asn]:[]); const decision=decide(a,permission,await rules(a.id),asn); if(decision==='deny')throw Object.assign(new Error('Permission denied'),{statusCode:403}); return {actor:a,decision};}
async function dispatch(req:any,reply:any,permission:string, target:{type:string;id?:string;serverId?:string}, execute:()=>Promise<unknown>){const {actor:who,decision}=await authorize(req,permission,target.serverId); if(decision==='approval_required'){const id=await requestApproval({requesterId:who.id,action:permission,targetType:target.type,targetId:target.id,serverId:target.serverId,payload:req.body,reason:(req.body as any)?.reason||'No reason supplied'});return reply.code(202).send({approvalRequestId:id,status:'pending'});} const out=await execute(); return reply.send(out);}
app.setErrorHandler((e:any,_req,reply)=>reply.code(e.statusCode||500).send({error:e.statusCode?e.message:'Service unavailable'}));
app.post('/api/auth/login',{config:{rateLimit:{max:5,timeWindow:'15 minutes'}}},async(req:any,reply)=>{const b=z.object({email:z.string().email(),password:z.string().min(1)}).parse(req.body); const [r]=await db.query<any[]>('SELECT u.*,roles.name role FROM users u JOIN roles ON roles.id=u.role_id WHERE email=? AND suspended=0',[b.email]); if(!r[0]||!await verifyPassword(b.password,r[0].password_hash))return reply.code(401).send({error:'Invalid credentials'});const s=await createSession(r[0].id);reply.setCookie('session',s.id,{httpOnly:true,sameSite:'strict',secure:process.env.NODE_ENV==='production',path:'/'});return {csrfToken:s.csrf,user:{id:r[0].id,email:r[0].email,role:r[0].role}};});
app.get('/api/servers',async(req:any)=>{const a=actor(req); const result:any=await gate.application('/servers?include=allocations'); if(a.role!== 'manager') return result; const [rows]=await db.query<any[]>('SELECT server_id FROM server_assignments WHERE user_id=?',[a.id]); const visible=new Set(rows.map(x=>x.server_id)); result.data=(result.data||[]).filter((s:any)=>visible.has(String(s.attributes?.id))||visible.has(String(s.attributes?.identifier))); return result;});
app.get('/api/servers/:id',async(req:any)=>{const id=z.string().parse(req.params.id);await authorize(req,'server.view',id);return gate.application(`/servers/${encodeURIComponent(id)}?include=allocations,variables`);});
const client=(path:string,permission:string,method='GET')=>app.route({method:method as any,url:path,handler:async(req:any,reply:any)=>{const id=req.params.id;return dispatch(req,reply,permission,{type:'server',id,serverId:id},()=>gate.client(`/servers/${encodeURIComponent(id)}${req.params.tail||''}`,{method,body:method==='GET'?undefined:JSON.stringify(req.body),headers:{'Content-Type':'application/json'}}));}});
client('/api/servers/:id/resources','resource.view'); client('/api/servers/:id/files/:tail*','files.view'); client('/api/servers/:id/backups','backup.view'); client('/api/servers/:id/databases','database.view'); client('/api/servers/:id/schedules','schedule.view'); client('/api/servers/:id/startup','startup.view'); client('/api/servers/:id/allocations','allocation.view');
app.post('/api/servers/:id/power',async(req:any,reply)=>{const signal=z.object({signal:z.enum(['start','stop','restart','kill'])}).parse(req.body).signal;return dispatch(req,reply,`console.${signal}`,{type:'server',id:req.params.id,serverId:req.params.id},()=>gate.client(`/servers/${req.params.id}/power`,{method:'POST',body:JSON.stringify({signal}),headers:{'Content-Type':'application/json'}}));});
app.post('/api/servers/:id/files/:tail*',async(req:any,reply)=>dispatch(req,reply,'files.write',{type:'file',id:req.params.tail,serverId:req.params.id},()=>gate.client(`/servers/${req.params.id}/files/${req.params.tail}`,{method:'POST',body:JSON.stringify(req.body),headers:{'Content-Type':'application/json'}})));
app.post('/api/approvals/:id/approve',async(req:any,reply)=>{const a=actor(req);if(a.role!=='owner')throw Object.assign(new Error('Owner required'),{statusCode:403});const [rows]=await db.query<any[]>('SELECT * FROM approval_requests WHERE id=?',[req.params.id]); const request=rows[0]; if(!request)throw Object.assign(new Error('Approval not found'),{statusCode:404}); const token=await claimApproval(req.params.id,a.id); try { const payload=JSON.parse(request.payload); if(request.action.startsWith('console.') && request.server_id) await gate.client(`/servers/${encodeURIComponent(request.server_id)}/power`,{method:'POST',body:JSON.stringify({signal:request.action.slice(8)}),headers:{'Content-Type':'application/json'}}); else if(request.action==='server.delete' && request.target_id) await gate.application(`/servers/${encodeURIComponent(request.target_id)}`,{method:'DELETE'}); else throw new Error('This approval action is not executable by the configured gateway'); await db.execute('INSERT INTO audit_logs(actor_id,action,resource_type,resource_id,server_id,result,request_id,metadata) VALUES(?,?,?,?,?,?,?,?)',[a.id,request.action,request.target_type,request.target_id,request.server_id,'success',req.id,JSON.stringify({approvalId:request.id,executionToken:token})]); return {status:'approved'}; } catch (error) { await db.execute('UPDATE approval_requests SET status="failed" WHERE id=? AND execution_token=?',[request.id,token]); throw error; }});
app.post('/api/approvals/:id/reject',async(req:any)=>{const a=actor(req);if(a.role!=='owner')throw Object.assign(new Error('Owner required'),{statusCode:403});const [x]=await db.execute<any>('UPDATE approval_requests SET status="rejected",reviewed_by=?,reviewed_at=NOW() WHERE id=? AND status="pending"',[a.id,req.params.id]);if(x.affectedRows!==1)throw Object.assign(new Error('Request is no longer pending'),{statusCode:409});return {status:'rejected'};});
app.get('/api/notifications',async(req:any)=>{const a=actor(req);const [r]=await db.query('SELECT id,type,title,body,read_at,created_at FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 50',[a.id]);return r;});
app.get('/',async(_req,reply)=>reply.sendFile('index.html'));
app.get('/healthz',async()=>({ok:true})); app.listen({host:process.env.HOST||'127.0.0.1',port:Number(process.env.PORT||7799)});
